###
###
###
###   Purpose:   Collection of tools for documents
###   started:   2016/02/03 (pvr)
###
### ################################################ ###

#' Create a course website
#'
#' @param psCourseName   Name of the course
#' @param psCourseDir    Course directory
#' @param psWsTemplate   Website template
#' @export create_course_website
create_course_website <- function(psCourseName, psCourseDir = ".", psWsTemplate = NULL){
  ### # specify the course package directory
  sCoursePackDir <- file.path(psCourseDir, psCourseName)
  ### # check that course package exists
  stopifnot(dir.exists(sCoursePackDir))
  ### # if template is not specified use a template from rmarkdown
  if (is.null(psWsTemplate)) {
    devtools::use_vignette(name = "index", pkg = sCoursePackDir)
  } else {
    sWsTemplate <- psWsTemplate
    file.copy(from = sWsTemplate, to = file.path(sCoursePackDir, "vignettes", "index.Rmd"), recursive = TRUE)
  }
  invisible(TRUE)
}


#' Create a course document
#'
#' @description
#' \code{create_course_document} assumes that psPkgPath is a
#' directory that contains an R-package. By default the new
#' document is created in subdirectory "vignettes". If this
#' subdirectory does not exist, it is created. The document
#' is generated by the function \code{rmarkdown::draft} using
#' the template "pdf_document".
#'
#' @details
#' The basic functionality follows the function
#' \code{devtools::use_vignette}, except for the possibility
#' of specifying any given template from any package. The template
#' can be specified via argument "psRmdTemplate". This requires
#' in the package given by psTemplatePkg that a subdirectory with
#' the name of the template exists under "rmarkdown/templates".
#' More information about setting up custom templates is obtained
#' in the helpfile of rmarkdown::draft.
#'
#' @param   psDocuName   name of the new document
#' @param   psPkgPath    path where package is located under which document should be created
#' @param   psRmdTemplate   name of the template to be used
#' @param   psTemplatePkg   package from where the template should be taken
#' @param   psDocuSubdir    subdirectory in which document should be saved to
#' @param   pbEdit          directly open newly created document
#' @export create_course_document
create_course_document <- function(psDocuName,
                                   psPkgPath     = ".",
                                   psRmdTemplate = "pdf_document",
                                   psTemplatePkg = "rcoursetools",
                                   psDocuSubdir  = "vignettes",
                                   pbEdit        = TRUE) {
  ### # do the preparation similar to devtools::use_vignette
  pkg <- devtools::as.package(psPkgPath)
  devtools:::check_suggested("rmarkdown")
  devtools:::add_desc_package(pkg, "Suggests", "knitr")
  devtools:::add_desc_package(pkg, "Suggests", "rmarkdown")
  devtools:::add_desc_package(pkg, "VignetteBuilder", "knitr")
  dir.create(file.path(pkg$path, psDocuSubdir), showWarnings = FALSE)
  sDocuPath <- file.path(pkg$path, psDocuSubdir, paste0(psDocuName, ".Rmd"))
  rmarkdown::draft(file = sDocuPath,
                   template = psRmdTemplate,
                   package = psTemplatePkg,
                   create_dir = FALSE,
                   edit = FALSE)
  if (pbEdit) file.edit(sDocuPath)
  message("Draft vignette created in ", sDocuPath)
}
